
version: '3'
services:
  userui:
    build:
      context: ./UserUI
    ports:
      - "5000:5000"
    depends_on:
      - redis
  analytics:
    build:
      context: ./Analytics
    ports:
      - "5001:5001"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
