apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-ui
  template:
    metadata:
      labels:
        app: user-ui
    spec:
      containers:
      - name: user-ui
        image: footballsurveyregistry.azurecr.io/football-survey-user-ui:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: user-ui
spec:
  selector:
    app: user-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
